[package]
name = "bobyard-fuel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
fuel-core-client = { version = "0.17.13", features = ["default", "dap"] }
tokio = { version = "1.29.1", features = ["full"] }
