[package]
name = "bobyard-fuel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tokio = { version = "1.29.1", features = ["full"] }
fuel-core-client = { version = "0.17.13", features = ["default", "dap"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
async-trait = "0.1.71"
futures = "0.3.28"
thiserror = "1.0.43"
rusoto_core = { version = "0.48.0", default_features = false, features = [
    "rustls",
] }
rusoto_sqs = { version = "0.48.0", default_features = false, features = [
    "rustls",
] }
rusoto_s3 = { version = "0.48.0", default_features = false, features = [
    "rustls",
] }
rusoto_dynamodb = { version = "0.48.0", default-features = false, features = [
    "rustls",
] }
